description: "The official website for Morse-Module."
name: "morse_module"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  import_sorter: "^2.0.0"
  local_google_fonts: "^1.0.8"
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.7.0 <3.0.0"
flutter:
  fonts:
    - family: "Source Code Pro"
      fonts:
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-200i.ttf"
          style: "italic"
          weight: 200
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-300i.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-400i.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-500i.ttf"
          style: "italic"
          weight: 500
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-600i.ttf"
          style: "italic"
          weight: 600
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-700i.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-900i.ttf"
          style: "italic"
          weight: 900
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-200.ttf"
          weight: 200
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-300.ttf"
          weight: 300
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-400.ttf"
          weight: 400
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-500.ttf"
          weight: 500
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-600.ttf"
          weight: 600
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-700.ttf"
          weight: 700
        - asset: "assets/fonts/googleFonts/Source-Code-Pro/Source-Code-Pro-900.ttf"
          weight: 900
  uses-material-design: true
google_fonts:
  docs: false
  fonts:
    - "Source Code Pro"
